volumes:
  mysql_data:
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_taxi_api
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taxi_api
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  taxi-api:
    build: .
    container_name: taxi_api_app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/taxi_api
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl-auto=update
  client-web:
    image: php:8.2-apache
    container_name: taxi_web_client
    ports:
      - "80:80"
    volumes:
      - ./src/main/php:/var/www/html
    depends_on:
      - taxi-api
  admin-console:
    build: ./admin-console
    container_name: taxi_api_admin
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_NAME=taxi_api
      - DB_USER=root
      - DB_PASS=password
